id: IB15BC473
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:52:29+00:00'
last_modified: '2022-06-08T17:18:50.020366+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17047
  title: རྡོ་རྗེ་འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་སྦྱིན་སྲེག་དང་གསོལ་འདེབས་བྱིན་རླབས་མྱུར་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F8F3:
      image_group_id: I8LS17053
      title: ''
      total_pages: 52
      order: 1
      base_file: F8F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
